cache:
  directories:
    - $HOME/.cache/rebar3
install: true
language: erlang
notifications:
  email: false
otp_release:
  - 22.1
  - 22.0
  - 21.3.8
  - 20.3
  - 19.3
  - 18.3
script: "make travis"
sudo: false